#!/bin/bash

RSCR=/opt/r_scripts/check_m.R
# RSCR=/home/daleb/singularity-def/autocorr/check_m.R

if [ "$#" -eq 0 ];
then
    NMC=1000
else
    NMC=$1
fi

array1=(0 .05 .10 .15 .20 .25)
array2=(0 .10 .20 .30 .40 .50)

for ((i=0;i<${#array1[@]};++i)); do
    k=`expr $i + 1`
    printf "(%s/%s) A = %.2f, B = %.2f, AB = %.2f\n" "$k" "${#array1[@]}" "${array1[i]}" "${array2[i]}" "${array2[i]}"
    for j in 1 4; do
	printf "      Running $NMC simulations of version %d of 8..." "$j"
	CMD="Rscript $RSCR $NMC ${array1[i]} ${array2[i]} ${array2[i]} $j"
	eval "$CMD"
	printf " DONE\n"
    done
done

echo "Simulations completed."
