#!/bin/bash

NMC=1000
RSCRIPTPATH=/usr/local/bin/Rscript
SCRIPTPATH=/opt/r_scripts/practice.R

function usage {
    echo "usage: "
    echo "  $0 -h -n xxxx -w yyyy -b zzzz"
    echo "where:"
    echo "  -h              show help screen"
    echo "  -n  xxxx        number of monte carlo runs (default 1000)"
}

while [ -n "$1" ]
do
    case "$1" in
	-h) usage
	    exit ;;
	-w) WIJ="$2"
	    shift ;;
	-b) BI="$2"
	    shift ;;
	-n) NMC="$2"
	    shift ;;
	*) usage
	   exit ;;
    esac
    shift
done

echo "Number of Monte Carlo runs: $NMC"

array1=(0 4 8 12 16 20) # within effect (0 - 20)
array2=(0 10 20 30 40 50) # between effect (0 - 50)

for ((i=0;i<${#array1[@]};++i)); do
    k=`expr $i + 1`
    printf "(%s/%s) within = %02d, between = %02d..." "$k" "${#array1[@]}" "${array1[i]}" "${array2[i]}"
    CMD="${RSCRIPTPATH} ${SCRIPTPATH} $NMC ${array1[i]} ${array2[i]}"
    EXECTIME=`(/usr/bin/time -f "%E" ${RSCRIPTPATH} ${SCRIPTPATH} $NMC ${array1[i]} ${array2[i]}) 2>&1`
    printf "DONE in $EXECTIME\n"
done

echo "Simulations completed."
