#!/bin/bash

NMC=1000

function usage {
    echo "usage: "
    echo "  $0 -h -n xxxx"
    echo "where:"
    echo "  -h              give help"
    echo "  -n  xxxx        number of monte carlo runs (default 1000)"
}

while [ -n "$1" ]
do
    case "$1" in
	-h) usage
	    exit ;;
	-n) NMC="$2"
	    shift ;;
	*) usage
	   exit ;;
    esac
    shift
done
   
echo "running stroop with nruns=$NMC"
echo "versions: ${VERS[@]}"

array1=(0 14 28 42 56 70)
array2=(0 44 88 132 176 220)

for ((i=0;i<${#array1[@]};++i)); do
    k=`expr $i + 1`
    printf "(%s/%s) B1 = %.2f, B2 = %.2f\n" "$k" "${#array1[@]}" "${array1[i]}" "${array2[i]}"
    CMD="stroop_fit $NMC ${array1[i]} ${array2[i]}"
    printf "      Running $NMC simulations... "
    EXECTIME=`(/usr/bin/time -f "%E" $CMD) 2>&1`
    printf "DONE in $EXECTIME\n"
done

echo "Simulations completed."
