#!/bin/bash

if [ $# -ne 6 ]; then
    BASE=`basename $0`
    1>&2 echo "usage:"
    1>&2 echo "  $BASE model version effect n_subjects raw_effect n_simulation_runs"
    1>&2 echo "      where model=(clmm,lmem)"
    1>&2 echo "            version=(asymptote,single)"
    1>&2 echo "            effect=(main,interaction)"
    1>&2 echo "            raw_effect is .14(=H1 true) or 0(=H0 true)"
    exit
fi

CMD="truthiness::power_sim('$1', '$2', '$3', $4, $5, $6)"
1>&2 echo "Running in R: "
1>&2 echo "  $CMD"
RDSFILE=`Rscript -e "$CMD"`

echo "$RDSFILE"
