#!/bin/bash

if [ $# -ne 8 ]; then
    BASE=`basename $0`
    1>&2 echo "usage:"
    1>&2 echo "  $BASE model p1 p2 p3 p4 target_effect n_subjects n_simulation_runs"
    1>&2 echo "      where model=(clmm,lmem)"
    1>&2 echo "            p1 p2 p3 p4=illusory-truth effect profile"
    1>&2 echo "            target_effect=(main,interaction)"
    exit
fi

CMD="truthiness::power_sim('$1', c($2, $3, $4, $5), '$6', $7, $8)"
1>&2 echo "Running in R: "
1>&2 echo "  $CMD"
RDSFILE=`Rscript -e "$CMD"`

echo "$RDSFILE"
