#!/bin/bash

Rscript -e "saveRDS(rnorm(10), '.testsim.rds')"
RES=`curl -s -F name=testsim.rds -F data=@.testsim.rds http://talklab.psy.gla.ac.uk/RData/upload.php`
rm .testsim.rds

if [ "$RES" = "Successfully uploaded testsim.rds" ]; then
    echo "Test succeeded."
else
    echo "TEST FAILED: $RES"
fi
